### ISSUE TITLE
[Bug] 覆盖安装提示External controller memory error

### ISSUE THREAD

**Issue by williechan91** [pompurin404/mihomo-party#10]
### Verify steps

- [X] 我未在[Issue Tracker](./?q=is%3Aissue)中寻找过我要提出的问题
- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 这是GUI程序的问题,而不是内核程序的问题
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11

### 发生问题 mihomo-party 版本

0.42

### 描述

![image](https://github.com/user-attachments/assets/2a06a6d6-a369-4d43-a862-999b5f4328db)
作者你好，从0.40升到0.41，从0.41升到0.42，覆盖安装后都报这个错误，只能卸载重装

### 重现方式

作者你好，从0.40升到0.41，从0.41升到0.42，覆盖安装后都报这个错误，只能卸载重装

**Comment by ghost** [comment]
https://github.com/pompurin404/mihomo-party/actions/runs/10366079671 试试这个

**Comment by williechan91** [comment]
> https://github.com/pompurin404/mihomo-party/actions/runs/10366079671 试试这个
安装完报错
```
Cannot read properties of undefined (reading 'icon')
TypeError: Cannot read properties of undefined (reading 'icon')
    at groupContent (file:///C:/Program%20Files/mihomo-party/resources/app.asar/out/renderer/assets/index-CZPimv-I.js:219890:39)
    at file:///C:/Program%20Files/mihomo-party/resources/app.asar/out/renderer/assets/index-CZPimv-I.js:218623:11
    at Array.map (<anonymous>)
    at VirtuosoItems (file:///C:/Program%20Files/mihomo-party/resources/app.asar/out/renderer/assets/index-CZPimv-I.js:218599:58)
    at Nh (file:///C:/Program%20Files/mihomo-party/resources/app.asar/out/renderer/assets/index-CZPimv-I.js:3382:8)
    at cj (file:///C:/Program%20Files/mihomo-party/resources/app.asar/out/renderer/assets/index-CZPimv-I.js:4036:7)
    at bj (file:///C:/Program%20Files/mihomo-party/resources/app.asar/out/renderer/assets/index-CZPimv-I.js:4012:10)
    at Vk (file:///C:/Program%20Files/mihomo-party/resources/app.asar/out/renderer/assets/index-CZPimv-I.js:6490:14)
    at Uk (file:///C:/Program%20Files/mihomo-party/resources/app.asar/out/renderer/assets/index-CZPimv-I.js:6019:11)
    at Tk (file:///C:/Program%20Files/mihomo-party/resources/app.asar/out/renderer/assets/index-CZPimv-I.js:6013:24)
```

**Comment by ghost** [comment]
0.4.3应该修复了

**Comment by williechan91** [comment]
> 0.4.3应该修复了

这个版本可以了
